# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b97f4430c64a8de9a41e01abe83b57d4b038eae472c668cd5ff092b48ae210d00482203381105c82d3113ccb053adffa948e9f9ec175c89cb467dc34fe14d1b9

test:
  secret_key_base: 4ebb79853135bf6e495f85ae350ffdaea07a27bff6a8b7789f88252184730fca82418155c697958f33365570f4dbfacd74989479e57b02ffd9eab6cb77eea2cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
